import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProvider from "./ClientProvider";
import { cookies } from "next/headers";
import { verify } from "jsonwebtoken";
import { Toaster } from "react-hot-toast";
import { Vazirmatn } from "next/font/google";
import BottomNav from "@/Components/bottomNav/BottomNav";
import Navbar from "@/Components/navbar/Navbar";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "bazarbin",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let userData = null
  const tokenCookie = (await cookies()).get('token')
  const token = tokenCookie?.value
  try {
    userData = verify(token, process.env.ACCESSTOKEN_SECRETKEY)
  } catch {
    userData = null
  }
  return (
    <html>
      <body
        dir="rtl"
        className={`${geistMono.variable} antialiased bg-zinc-900`}
      >
        <ClientProvider userData={userData}>
          <Navbar />
          {children}
          <BottomNav />
          <Toaster />
        </ClientProvider>
      </body>
    </html>
  );
}
